#!/bin/bash
echo "-----------------Waiting for Process--------------------"
sed '1,$d' /root/test1.txt > test1.txt  
md5sum ./uploadfile/*.exe | awk '{print $1}' > /root/test1.txt 
foo = "wc -c /root/output.txt | awk '{print $1}'"
value = `expr $foo`

if [ $value -gt 232 ]; then   
        sed '1,$d' /root/test1.txt > /root/test1.txt
        rm ./uploadfile/*.* 
       echo "check"
elif[ $value -le 232 ]; then 
        #PEview Peinfo Execute                                                               
        echo "check"
        rm ./uploadfile/*.*
else
        echo "Not Response"
    
echo "-------------------End Process--------------------------"
fi


